### ISSUE TITLE
Non-email app shows up in chooser (PayPal)

### ISSUE THREAD

**Issue by gazedash** [cketti/EmailIntentBuilder#12]
I know it is not your problem, but PayPal is shown in choser alongside email client. It shouldn't be the case.
I'm fighting with this stupid case for quite some time myself...

**Comment by cketti** [comment]
They probably added support for mailto: URIs because they allow sending money to an email address. You could do some extra work to try to figure out which apps are truly email apps and/or filter out the PayPal app. But I wouldn't bother. Users will pick the right app for the use case.

**Comment by gazedash** [comment]
OK, thanks for the response. Do you know by any chance how can I filter it out? ;) Otherwise, nevermind

Just to comment further on the "Paypal case" & why I think it matters, 
<details>

  <summary>if you're interested</summary>

On one hand I agree that I wouldn't bother. But 
1) client wants to fix this bug 
2) imagine a scenario where someone who is not super familiar with this selects PayPal and what's worse person then sets it as default choice (by accident)? 
3) it looks super cheesy, even for me, to include PayPal when I want to send an email to our support service. In this case it doesn't make any sense to include PayPal. OK I get that, PayPal somehow supports sending something by email, but still, it shouldn't justify this behavior. 
4) Other malicious apps or apps that in no way related to receiving emails can act as phishing tools
5) What if every financial service had this feature? I don't think it is cool to sort through money sending apps when all you want to do is just send an email
</details>

**Comment by cketti** [comment]
It boils down to writing you own Activity chooser component. You can use `PackageManager` to query for apps that support the `mailto:` URI. Then manually remove PayPal from that list. Or you could only show apps that support the `mailto:` URI and that support the `android.intent.action.MAIN` action with the `android.intent.category.APP_EMAIL` category. But you should do extensive testing to make sure all popular email apps support that.

Despite having a custom chooser you'll probably still want the user to be able to select a default app. You'll have to build that mechanism yourself, too. And you should probably also provide a way to remove/change the default app choice.

**Comment by gazedash** [comment]
Nothing worked to filter out unneeded apps except "Intent.EXTRA_EXCLUDE_COMPONENTS", I am not an android developer and I missed this out, I didn't see it on StackOverflow. But now I solve my issue.

```
    @ReactMethod
    public void sendEmail(String email, String subject, String bodyText) {
        String mailto = "mailto:" + email +
                "&subject=" + Uri.encode(subject) +
                "&body=" + Uri.encode(bodyText);

        Intent i = new Intent(Intent.ACTION_SENDTO, Uri.parse(mailto));
        i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

        PackageManager pm = getCurrentActivity().getPackageManager();

        List<ResolveInfo> resInfo = pm.queryIntentActivities(i, 0);

        ArrayList<ComponentName> targets = new ArrayList<>();

        for (int ii = 0; ii < resInfo.size(); ii++) {
            ResolveInfo ri = resInfo.get(ii);
            String packageName = ri.activityInfo.packageName;

            ComponentName cm = new ComponentName(packageName, ri.activityInfo.name);
            if(packageName.contains("paypal")) {
                targets.add(cm);
            }
        }

        Intent openInChooser = Intent.createChooser(i, "Send to");
        if (targets.size() > 0) {
            openInChooser.putExtra(Intent.EXTRA_EXCLUDE_COMPONENTS, targets.toArray(new ComponentName[0]));
        }

        getCurrentActivity().startActivity(openInChooser);
    }
```

Also for some reason either the Google's doc is outdated or just wrong.
https://developer.android.com/guide/components/intents-common.html?authuser=2#Email

**Comment by cketti** [comment]
For people who stumble over this in the future, here's a list of things to consider when using the approach from the previous comment:
- [`EXTRA_EXCLUDE_COMPONENTS`](https://developer.android.com/reference/kotlin/android/content/Intent#extra_exclude_components) is only available since API 24. 
- Using the system's chooser (`Intent.createChooser()`) has the downside of the user not being able to choose a default app.
- If you use `targetSdkVersion 30` (and soon you'll have to if you intend to publish on the Play Store) `PackageManager` will only return results (on Android 11+) if you make the correct entries in the `<queries>` element in `AndroidManifest.xml`. See https://developer.android.com/about/versions/11/privacy/package-visibility
