### ISSUE TITLE
Line breaks in body not working for Gmail app

### ISSUE THREAD

**Issue by joernahrens** [cketti/EmailIntentBuilder#8]
Hi, I'm doing something like this:

```
val intent = EmailIntentBuilder.from(it)
  .to("someone@somewhere.com")
  .subject("Hi!")
  .body("\nContains\nline breaks!\n")
  .build()
```

Using this intent shows the line breaks in the Samsung mail client and also in Outlook for Android. But Gmail seems to not understand the line breaks. 

Receiving that email sent via Gmail I can see that it contains plain text AND html mail. 
The **html part** contains the line breaks (without any effect, because.. html 😉 ). The **text part** doesn't contain the line breaks. 

Is this some weird misbehavior of Gmail anyone faced before? I'm using the current version published on 12.02.2020.

**Comment by cketti** [comment]
It's a bug in Gmail. I've already reported it using the "send feedback" functionality of the Gmail app some time ago. It might help to do the same.

**Comment by joernahrens** [comment]
Will do that, thanks!
